### ISSUE TITLE
Design Home Page

### ISSUE THREAD

**Issue by waahm7** [waahm7/team-42-codeu#37]
We need to design a home page to show our users as the first page.

**Comment by azanbinzahid** [comment]
**The Background**
It should be lightweight, non-textured, more transparent or light colored. This one is really dark with white lines affecting our text and other elements.

![Capture](https://user-images.githubusercontent.com/47540683/59539631-70bd8880-8f17-11e9-86ff-41c39d3b8f0c.JPG)

Pictures should be more professional looking. The text is not appealing to picture as white clashing with white. Font is also very simple.

![Capture2](https://user-images.githubusercontent.com/47540683/59539689-a6627180-8f17-11e9-9745-ff0aac105786.JPG)
The Slides have no border or widescreen div makes them look unprofessional and just an add-on screen.

![Capture3](https://user-images.githubusercontent.com/47540683/59540066-00fbcd80-8f18-11e9-84a1-3b409010fd9a.JPG)
These could be colored themed and again the background is affecting the text. The text might have its own background and it should be consistent in styling i.e. size, style, color, etc.


**Solution**
Designing custom HTML page/css is a very tedious task and requires a lot of consistency. The best practice is to use already made nice-looking templates which are very elegant and eye-catching. Let me know if you want to revamp, I'll use a template which will solve most of the mistakes otherwise let's just work together to correct every single component.

**Comment by waahm7** [comment]
@azanbinzahid Excelent feedback! especially the pictures makes it really easy to understand. I agree with everything you said but I think we should create a new issue with title something like design page version 2. This design was great as version 1 and solves the given issue that was to design a homepage. Now we can focus on improving it!

**Comment by waahm7** [comment]
Let's open a new issue and we can assign it to either @azanbinzahid or @froheel. Whatever you guys decide!

**Comment by froheel** [comment]
@waahm7 @azanbinzahid I will solve the issues you guys have mentioned. It is just instead of using an already made template, we should try to learn something and experiment with css. I made the page myself and It does have a lot of issues like un professional pictures and the text is not visible with the background. However, I will try my best to solve those. I don't see any point in using an already made template. Ill ask you guys if I need help. Thanks for the feedback ! will keep this in mind when I make home page version 2
